server:
  port: 8080

spring:
  application:
    name: autonest-api
  threads:
    virtual:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:mysql://localhost:3306/autonest?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: autonest
    password: autonest123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

springdoc:
  api-docs:
    path: /v3/api-docs

autonest:
  cors:
    allowed-origins:
      - http://localhost:4200
  auth:
    cookie:
      secure: false
      same-site: Strict
  upload-dir: uploads

logging:
  level:
    org.hibernate.SQL: warn
